schema: http://localhost:1337/graphql
documents: ./apollo/**/*.gql
generates:
  types/graphql.d.ts:
    - typescript-graphql-files-modules
  types/types.ts:
    - typescript
    - typescript-operations